### PR TITLE
Add alternate temperature conversion for big_forecast

### PR DESCRIPTION
**Pull request by micahyoung**
* Allow alternate temp conversion for any location
* Use alternate temp for NYC
* Update layout of big_forecast to correctly position alt temp
* Alternate temperature data will be available to all widgets but will only currently appear in big_forecast

Rationale: New York seems to have a disproportionate number of non-native Fahrenheit readers and it could benefit all of us to develop a bit of short hand knowledge for both.

### CODE REVIEW

**Comment by spilth** [comment]
Hey Micah. This looks great. Thanks for doing this!

One question: I don't see the NYC dashboard actually using this yet. Did you forget to check in dashboards/nyc.erb?

**Comment by micahyoung** [comment]
I hadn't actually pushed it up yet. If it looks ok, I'll merge the pull request and get it up there.

**Comment by spilth** [comment]
Cool. Thanks!

**Comment by micahyoung** [comment]
I realized the alt units looked strange without the °C/°F units so with the last commit now it does, though a side-effect is that it does so for both big_forecast and forecast. I smoke-tested each board on staging and I think they look better with the units but we can change this if needed.

**Comment by micahyoung** [comment]
@spilth Deployed to pivotal-life. Let me know what you think.

**Comment by spilth** [comment]
Looks good! I put it back up on the NYC monitor.

**Pull request merged**
